Connected to venv (Python 3.9.25)

In [ ]:
import pandas as pd

path = "Eval_Run_11-03-2026_13-23/final_results_summery.csv"
results = pd.read_csv(path)

results

,Experiment,Variable,RMSE,R2,NLL,95 %_Coverage
0,latitude_longitude_AOD_nn_PM2.5_nn____AOD_PM2.5,AOD,1.950297,-28.387583,877.425200,0.000000
1,latitude_longitude_AOD_nn_PM2.5_nn____AOD_PM2.5,PM2.5,1738.982389,-3269.395264,38505.105000,0.000000
2,latitude_longitude_AOD_nn_PM2.5_nn____AOD,AOD,0.629668,-1.920278,90.220710,0.009257
3,latitude_longitude_AOD_nn_PM2.5_nn____PM2.5,PM2.5,1527.450736,-2750.251465,29706.924000,0.000000
4,latitude_longitude_AOD_nn____AOD_PM2.5,AOD,0.458591,-0.740453,47.206060,0.511371
5,latitude_longitude_AOD_nn____AOD_PM2.5,PM2.5,43.594583,-1.033503,1.187249,0.511371
6,latitude_longitude_AOD_nn____AOD,AOD,0.461370,-0.661525,47.796740,0.018400
7,latitude_longitude_AOD_nn____PM2.5,PM2.5,35.254498,-0.399538,0.886429,0.987886
8,latitude_longitude_PM2.5_nn____AOD_PM2.5,AOD,0.362282,0.013557,1.927887,0.500000
9,latitude_longitude_PM2.5_nn____AOD_PM2.5,PM2.5,1727.103717,-3316.278809,37980.363000,0.500000
10,latitude_longitude_PM2.5_nn____AOD,AOD,0.535650,-1.199138,1.527683,0.957029
11,latitude_longitude_PM2.5_nn____PM2.5,PM2.5,1993.641831,-3961.406738,50608.777000,0.000000
12,latitude_longitude____AOD_PM2.5,AOD,0.391924,-0.028798,1.389753,0.974300
13,latitude_longitude____AOD_PM2.5,PM2.5,51.871974,-2.659040,0.924974,0.974300
14,latitude_longitude____AOD,AOD,0.386900,-0.010693,1.384607,0.956647
15,latitude_longitude____PM2.5,PM2.5,46.566498,-1.912223,0.814528,0.998377

In [ ]:
import pandas as pd

path = "Eval_Run_11-03-2026_14-47/final_results_summery.csv"
results = pd.read_csv(path)

results

,Experiment,Variable,RMSE,R2,NLL,95 %_Coverage
0,latitude_longitude____AOD_PM2.5,AOD,0.392441,-0.032780,1.390707,0.974058
1,latitude_longitude____AOD_PM2.5,PM2.5,52.098104,-2.572429,0.929395,0.974058
2,latitude_longitude____AOD,AOD,0.385701,-0.015859,1.387599,0.956329
3,latitude_longitude____PM2.5,PM2.5,46.662189,-1.908323,0.816146,0.998493

In [ ]:
import pandas as pd

path = "Eval_Run_11-03-2026_15-01/final_results_summery.csv"
results = pd.read_csv(path)

results

,Experiment,Variable,RMSE,R2,NLL,95 %_Coverage
0,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,AOD,1.655571,-17.780285,867.210700,0.003053
1,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,PM2.5,2486.335858,-9434.530273,40778.610000,0.003053
2,latitude_longitude_AOD_idw_PM2.5_idw____AOD,AOD,0.538196,-0.974615,90.407790,0.036298
3,latitude_longitude_AOD_idw_PM2.5_idw____PM2.5,PM2.5,2198.402829,-7322.518555,31880.361000,0.000000
4,latitude_longitude_AOD_idw____AOD_PM2.5,AOD,0.378270,0.008072,43.960808,0.554255
5,latitude_longitude_AOD_idw____AOD_PM2.5,PM2.5,59.002338,-4.272814,1.174576,0.554255
6,latitude_longitude_AOD_idw____AOD,AOD,0.377013,0.004898,43.659970,0.109489
7,latitude_longitude_AOD_idw____PM2.5,PM2.5,41.488806,-1.631923,0.783371,0.999872
8,latitude_longitude_PM2.5_idw____AOD_PM2.5,AOD,0.367400,0.088612,2.013462,0.495574
9,latitude_longitude_PM2.5_idw____AOD_PM2.5,PM2.5,2497.089105,-9429.868164,41131.800000,0.495574
10,latitude_longitude_PM2.5_idw____AOD,AOD,0.530764,-0.940924,1.684192,0.928617
11,latitude_longitude_PM2.5_idw____PM2.5,PM2.5,2839.247700,-12361.732422,53176.880000,0.000000
12,latitude_longitude____AOD_PM2.5,AOD,0.390134,-0.026211,1.385191,0.974725
13,latitude_longitude____AOD_PM2.5,PM2.5,51.793995,-2.617803,0.923629,0.974725
14,latitude_longitude____AOD,AOD,0.386820,-0.016022,1.386027,0.958367
15,latitude_longitude____PM2.5,PM2.5,46.601816,-1.898370,0.814554,0.998783

In [ ]:
import pandas as pd

path = "Eval_Run_11-03-2026_15-33/final_results_summery.csv"
results = pd.read_csv(path)

results

,Experiment,Variable,RMSE,R2,NLL,95 %_Coverage
0,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,AOD,1.698249,-19.389364,883.999200,0.002564
1,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,PM2.5,2456.666746,-8950.567383,40778.906000,0.002564
2,latitude_longitude_AOD_idw_PM2.5_idw____AOD,AOD,0.560506,-1.191653,95.063280,0.031447
3,latitude_longitude_AOD_idw_PM2.5_idw____PM2.5,PM2.5,2172.735258,-7084.269531,31897.200000,0.000000
4,latitude_longitude_AOD_idw____AOD_PM2.5,AOD,0.393674,-0.066424,46.193954,0.547383
5,latitude_longitude_AOD_idw____AOD_PM2.5,PM2.5,58.582876,-4.179104,1.176666,0.547383
6,latitude_longitude_AOD_idw____AOD,AOD,0.392455,-0.039915,45.899776,0.092426
7,latitude_longitude_AOD_idw____PM2.5,PM2.5,41.515224,-1.564974,0.790191,0.999745
8,latitude_longitude_PM2.5_idw____AOD_PM2.5,AOD,0.364207,0.090763,2.003989,0.496915
9,latitude_longitude_PM2.5_idw____AOD_PM2.5,PM2.5,2459.680467,-9161.356445,40878.723000,0.496915
10,latitude_longitude_PM2.5_idw____AOD,AOD,0.524437,-0.903666,1.648470,0.936404
11,latitude_longitude_PM2.5_idw____PM2.5,PM2.5,2808.635612,-12004.350586,53301.240000,0.000000
12,latitude_longitude____AOD_PM2.5,AOD,0.388660,-0.028098,1.381305,0.974372
13,latitude_longitude____AOD_PM2.5,PM2.5,51.893008,-2.658304,0.925605,0.974372
14,latitude_longitude____AOD,AOD,0.386819,-0.011551,1.385611,0.955981
15,latitude_longitude____PM2.5,PM2.5,46.610378,-1.906082,0.815273,0.998386

In [ ]:
import pandas as pd

path = "Eval_Run_11-03-2026_15-57/final_results_summery.csv"
results = pd.read_csv(path)

results

,Experiment,Variable,RMSE,R2,NLL,95 %_Coverage
0,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,AOD,1.698249,-19.389364,883.999200,0.002564
1,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,PM2.5,2456.666746,-8950.567383,40778.906000,0.002564
2,latitude_longitude_AOD_idw_PM2.5_idw____AOD,AOD,0.560506,-1.191653,95.063280,0.031447
3,latitude_longitude_AOD_idw_PM2.5_idw____PM2.5,PM2.5,2172.735258,-7084.269531,31897.200000,0.000000
4,latitude_longitude_AOD_idw____AOD_PM2.5,AOD,0.393674,-0.066424,46.193954,0.547383
5,latitude_longitude_AOD_idw____AOD_PM2.5,PM2.5,58.582876,-4.179104,1.176666,0.547383
6,latitude_longitude_AOD_idw____AOD,AOD,0.392455,-0.039915,45.899776,0.092426
7,latitude_longitude_AOD_idw____PM2.5,PM2.5,41.515224,-1.564974,0.790191,0.999745
8,latitude_longitude_PM2.5_idw____AOD_PM2.5,AOD,0.364207,0.090763,2.003989,0.496915
9,latitude_longitude_PM2.5_idw____AOD_PM2.5,PM2.5,2459.680467,-9161.356445,40878.723000,0.496915
10,latitude_longitude_PM2.5_idw____AOD,AOD,0.524437,-0.903666,1.648470,0.936404
11,latitude_longitude_PM2.5_idw____PM2.5,PM2.5,2808.635612,-12004.350586,53301.240000,0.000000
12,latitude_longitude____AOD_PM2.5,AOD,0.388660,-0.028098,1.381305,0.974372
13,latitude_longitude____AOD_PM2.5,PM2.5,51.893008,-2.658304,0.925605,0.974372
14,latitude_longitude____AOD,AOD,0.386819,-0.011551,1.385611,0.955981
15,latitude_longitude____PM2.5,PM2.5,46.610378,-1.906082,0.815273,0.998386
16,latitude_longitude_AOD_PM2.5_idw____AOD_PM2.5,AOD,1.570344,-16.182436,755.654360,0.010021
17,latitude_longitude_AOD_PM2.5_idw____AOD_PM2.5,PM2.5,2438.672487,-8846.370117,40183.690000,0.010021
18,latitude_longitude_AOD_PM2.5_idw____AOD,AOD,0.327303,0.247015,31.503624,0.251511
19,latitude_longitude_AOD_PM2.5_idw____PM2.5,PM2.5,2180.088301,-7038.937012,32113.475000,0.000000

In [ ]:
import pandas as pd

path = "Eval_Run_11-03-2026_21-11/final_results_summery.csv"
results = pd.read_csv(path)

results

,Experiment,Variable,RMSE,R2,NLL,95 %_Coverage
0,latitude_longitude____AOD_PM2.5,AOD,0.387108,-0.024108,1.377976,0.976077
1,latitude_longitude____AOD_PM2.5,PM2.5,51.447697,-2.583570,0.917753,0.976077
2,latitude_longitude____AOD,AOD,0.385105,-0.011087,1.381840,0.956715
3,latitude_longitude____PM2.5,PM2.5,46.056669,-1.793430,0.826152,0.998696
4,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,AOD,0.102805,0.928396,-0.026102,0.937787
5,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,PM2.5,15.485785,0.640094,-0.466338,0.937787
6,latitude_longitude_AOD_idw_PM2.5_idw____AOD,AOD,0.103054,0.927356,0.005656,0.913830
7,latitude_longitude_AOD_idw_PM2.5_idw____PM2.5,PM2.5,15.768426,0.637364,-0.461527,0.946085
8,latitude_longitude_AOD_idw____AOD_PM2.5,AOD,0.102780,0.925433,0.009572,0.951575
9,latitude_longitude_AOD_idw____AOD_PM2.5,PM2.5,68.707650,-6.048546,1.236406,0.951575
10,latitude_longitude_AOD_idw____AOD,AOD,0.103928,0.926283,0.002017,0.909149
11,latitude_longitude_AOD_idw____PM2.5,PM2.5,47.125163,-2.343398,0.860897,1.000000
12,latitude_longitude_PM2.5_idw____AOD_PM2.5,AOD,0.437909,-0.306370,1.562632,0.944809
13,latitude_longitude_PM2.5_idw____AOD_PM2.5,PM2.5,15.479623,0.636138,-0.481724,0.944809
14,latitude_longitude_PM2.5_idw____AOD,AOD,0.397832,-0.081148,1.426616,0.947511
15,latitude_longitude_PM2.5_idw____PM2.5,PM2.5,15.466274,0.642309,-0.481875,0.951255

In [ ]:
path = "Eval_Run_11-03-2026_21-11/final_results_summery.csv"
results = pd.read_csv(path)

results

,Experiment,Variable,RMSE,R2,NLL,95 %_Coverage
0,latitude_longitude____AOD_PM2.5,AOD,0.387108,-0.024108,1.377976,0.976077
1,latitude_longitude____AOD_PM2.5,PM2.5,51.447697,-2.583570,0.917753,0.976077
2,latitude_longitude____AOD,AOD,0.385105,-0.011087,1.381840,0.956715
3,latitude_longitude____PM2.5,PM2.5,46.056669,-1.793430,0.826152,0.998696
4,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,AOD,0.102805,0.928396,-0.026102,0.937787
5,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,PM2.5,15.485785,0.640094,-0.466338,0.937787
6,latitude_longitude_AOD_idw_PM2.5_idw____AOD,AOD,0.103054,0.927356,0.005656,0.913830
7,latitude_longitude_AOD_idw_PM2.5_idw____PM2.5,PM2.5,15.768426,0.637364,-0.461527,0.946085
8,latitude_longitude_AOD_idw____AOD_PM2.5,AOD,0.102780,0.925433,0.009572,0.951575
9,latitude_longitude_AOD_idw____AOD_PM2.5,PM2.5,68.707650,-6.048546,1.236406,0.951575
10,latitude_longitude_AOD_idw____AOD,AOD,0.103928,0.926283,0.002017,0.909149
11,latitude_longitude_AOD_idw____PM2.5,PM2.5,47.125163,-2.343398,0.860897,1.000000
12,latitude_longitude_PM2.5_idw____AOD_PM2.5,AOD,0.437909,-0.306370,1.562632,0.944809
13,latitude_longitude_PM2.5_idw____AOD_PM2.5,PM2.5,15.479623,0.636138,-0.481724,0.944809
14,latitude_longitude_PM2.5_idw____AOD,AOD,0.397832,-0.081148,1.426616,0.947511
15,latitude_longitude_PM2.5_idw____PM2.5,PM2.5,15.466274,0.642309,-0.481875,0.951255

In [ ]:
import pandas as pd

path = "Eval_Run_11-03-2026_21-11/final_results_summery.csv"
results = pd.read_csv(path)

results

,Experiment,Variable,RMSE,R2,NLL,95 %_Coverage
0,latitude_longitude____AOD_PM2.5,AOD,0.387108,-0.024108,1.377976,0.976077
1,latitude_longitude____AOD_PM2.5,PM2.5,51.447697,-2.583570,0.917753,0.976077
2,latitude_longitude____AOD,AOD,0.385105,-0.011087,1.381840,0.956715
3,latitude_longitude____PM2.5,PM2.5,46.056669,-1.793430,0.826152,0.998696
4,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,AOD,0.102805,0.928396,-0.026102,0.937787
5,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,PM2.5,15.485785,0.640094,-0.466338,0.937787
6,latitude_longitude_AOD_idw_PM2.5_idw____AOD,AOD,0.103054,0.927356,0.005656,0.913830
7,latitude_longitude_AOD_idw_PM2.5_idw____PM2.5,PM2.5,15.768426,0.637364,-0.461527,0.946085
8,latitude_longitude_AOD_idw____AOD_PM2.5,AOD,0.102780,0.925433,0.009572,0.951575
9,latitude_longitude_AOD_idw____AOD_PM2.5,PM2.5,68.707650,-6.048546,1.236406,0.951575
10,latitude_longitude_AOD_idw____AOD,AOD,0.103928,0.926283,0.002017,0.909149
11,latitude_longitude_AOD_idw____PM2.5,PM2.5,47.125163,-2.343398,0.860897,1.000000
12,latitude_longitude_PM2.5_idw____AOD_PM2.5,AOD,0.437909,-0.306370,1.562632,0.944809
13,latitude_longitude_PM2.5_idw____AOD_PM2.5,PM2.5,15.479623,0.636138,-0.481724,0.944809
14,latitude_longitude_PM2.5_idw____AOD,AOD,0.397832,-0.081148,1.426616,0.947511
15,latitude_longitude_PM2.5_idw____PM2.5,PM2.5,15.466274,0.642309,-0.481875,0.951255

In [ ]:
import pandas as pd

path = "Eval_Run_11-03-2026_21-11/final_results_summery.csv"
results = pd.read_csv(path)

results

,Experiment,Variable,RMSE,R2,NLL,95 %_Coverage
0,latitude_longitude____AOD_PM2.5,AOD,0.387108,-0.024108,1.377976,0.976077
1,latitude_longitude____AOD_PM2.5,PM2.5,51.447697,-2.583570,0.917753,0.976077
2,latitude_longitude____AOD,AOD,0.385105,-0.011087,1.381840,0.956715
3,latitude_longitude____PM2.5,PM2.5,46.056669,-1.793430,0.826152,0.998696
4,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,AOD,0.102805,0.928396,-0.026102,0.937787
5,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,PM2.5,15.485785,0.640094,-0.466338,0.937787
6,latitude_longitude_AOD_idw_PM2.5_idw____AOD,AOD,0.103054,0.927356,0.005656,0.913830
7,latitude_longitude_AOD_idw_PM2.5_idw____PM2.5,PM2.5,15.768426,0.637364,-0.461527,0.946085
8,latitude_longitude_AOD_idw____AOD_PM2.5,AOD,0.102780,0.925433,0.009572,0.951575
9,latitude_longitude_AOD_idw____AOD_PM2.5,PM2.5,68.707650,-6.048546,1.236406,0.951575
10,latitude_longitude_AOD_idw____AOD,AOD,0.103928,0.926283,0.002017,0.909149
11,latitude_longitude_AOD_idw____PM2.5,PM2.5,47.125163,-2.343398,0.860897,1.000000
12,latitude_longitude_PM2.5_idw____AOD_PM2.5,AOD,0.437909,-0.306370,1.562632,0.944809
13,latitude_longitude_PM2.5_idw____AOD_PM2.5,PM2.5,15.479623,0.636138,-0.481724,0.944809
14,latitude_longitude_PM2.5_idw____AOD,AOD,0.397832,-0.081148,1.426616,0.947511
15,latitude_longitude_PM2.5_idw____PM2.5,PM2.5,15.466274,0.642309,-0.481875,0.951255

In [ ]:
import pandas as pd

path = "Eval_Run_11-03-2026_21-11/final_results_summery.csv"
results = pd.read_csv(path)

results

,Experiment,Variable,RMSE,R2,NLL,95 %_Coverage
0,latitude_longitude____AOD_PM2.5,AOD,0.387108,-0.024108,1.377976,0.976077
1,latitude_longitude____AOD_PM2.5,PM2.5,51.447697,-2.583570,0.917753,0.976077
2,latitude_longitude____AOD,AOD,0.385105,-0.011087,1.381840,0.956715
3,latitude_longitude____PM2.5,PM2.5,46.056669,-1.793430,0.826152,0.998696
4,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,AOD,0.102805,0.928396,-0.026102,0.937787
5,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,PM2.5,15.485785,0.640094,-0.466338,0.937787
6,latitude_longitude_AOD_idw_PM2.5_idw____AOD,AOD,0.103054,0.927356,0.005656,0.913830
7,latitude_longitude_AOD_idw_PM2.5_idw____PM2.5,PM2.5,15.768426,0.637364,-0.461527,0.946085
8,latitude_longitude_AOD_idw____AOD_PM2.5,AOD,0.102780,0.925433,0.009572,0.951575
9,latitude_longitude_AOD_idw____AOD_PM2.5,PM2.5,68.707650,-6.048546,1.236406,0.951575
10,latitude_longitude_AOD_idw____AOD,AOD,0.103928,0.926283,0.002017,0.909149
11,latitude_longitude_AOD_idw____PM2.5,PM2.5,47.125163,-2.343398,0.860897,1.000000
12,latitude_longitude_PM2.5_idw____AOD_PM2.5,AOD,0.437909,-0.306370,1.562632,0.944809
13,latitude_longitude_PM2.5_idw____AOD_PM2.5,PM2.5,15.479623,0.636138,-0.481724,0.944809
14,latitude_longitude_PM2.5_idw____AOD,AOD,0.397832,-0.081148,1.426616,0.947511
15,latitude_longitude_PM2.5_idw____PM2.5,PM2.5,15.466274,0.642309,-0.481875,0.951255

In [ ]:
import pandas as pd

path = "Eval_Run_12-03-2026_13-30/final_results_summery.csv"
results = pd.read_csv(path)

results

,Experiment,Variable,RMSE,R2,NLL,95 %_Coverage
0,latitude_longitude____AOD_PM2.5,AOD,0.387108,-0.024108,1.377976,0.976077
1,latitude_longitude____AOD_PM2.5,PM2.5,51.447697,-2.583570,0.917753,0.976077
2,latitude_longitude____AOD,AOD,0.385105,-0.011087,1.381840,0.956715
3,latitude_longitude____PM2.5,PM2.5,46.056669,-1.793430,0.826152,0.998696
4,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,AOD,0.104006,0.923181,0.009670,0.935970
5,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,PM2.5,16.535202,0.635638,-0.389380,0.935970
6,latitude_longitude_AOD_idw_PM2.5_idw____AOD,AOD,0.105540,0.921575,0.032043,0.923061
7,latitude_longitude_AOD_idw_PM2.5_idw____PM2.5,PM2.5,16.490399,0.634101,-0.411799,0.949212
8,latitude_longitude_AOD_idw____AOD_PM2.5,AOD,0.105008,0.923514,0.042066,0.954061
9,latitude_longitude_AOD_idw____AOD_PM2.5,PM2.5,68.127913,-5.059235,1.237866,0.954061
10,latitude_longitude_AOD_idw____AOD,AOD,0.104234,0.923921,0.042957,0.900879
11,latitude_longitude_AOD_idw____PM2.5,PM2.5,48.467889,-2.155317,0.864705,0.998879
12,latitude_longitude_PM2.5_idw____AOD_PM2.5,AOD,0.441252,-0.347313,1.564369,0.943939
13,latitude_longitude_PM2.5_idw____AOD_PM2.5,PM2.5,16.696321,0.629061,-0.396571,0.943939
14,latitude_longitude_PM2.5_idw____AOD,AOD,0.397182,-0.104703,1.419147,0.953909
15,latitude_longitude_PM2.5_idw____PM2.5,PM2.5,16.654114,0.632574,-0.395904,0.949939

In [ ]:
import pandas as pd

path = "Eval_Run_11-03-2026_15-57/final_results_summery.csv"
results = pd.read_csv(path)

results

,Experiment,Variable,RMSE,R2,NLL,95 %_Coverage
0,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,AOD,1.698249,-19.389364,883.999200,0.002564
1,latitude_longitude_AOD_idw_PM2.5_idw____AOD_PM2.5,PM2.5,2456.666746,-8950.567383,40778.906000,0.002564
2,latitude_longitude_AOD_idw_PM2.5_idw____AOD,AOD,0.560506,-1.191653,95.063280,0.031447
3,latitude_longitude_AOD_idw_PM2.5_idw____PM2.5,PM2.5,2172.735258,-7084.269531,31897.200000,0.000000
4,latitude_longitude_AOD_idw____AOD_PM2.5,AOD,0.393674,-0.066424,46.193954,0.547383
5,latitude_longitude_AOD_idw____AOD_PM2.5,PM2.5,58.582876,-4.179104,1.176666,0.547383
6,latitude_longitude_AOD_idw____AOD,AOD,0.392455,-0.039915,45.899776,0.092426
7,latitude_longitude_AOD_idw____PM2.5,PM2.5,41.515224,-1.564974,0.790191,0.999745
8,latitude_longitude_PM2.5_idw____AOD_PM2.5,AOD,0.364207,0.090763,2.003989,0.496915
9,latitude_longitude_PM2.5_idw____AOD_PM2.5,PM2.5,2459.680467,-9161.356445,40878.723000,0.496915
10,latitude_longitude_PM2.5_idw____AOD,AOD,0.524437,-0.903666,1.648470,0.936404
11,latitude_longitude_PM2.5_idw____PM2.5,PM2.5,2808.635612,-12004.350586,53301.240000,0.000000
12,latitude_longitude____AOD_PM2.5,AOD,0.388660,-0.028098,1.381305,0.974372
13,latitude_longitude____AOD_PM2.5,PM2.5,51.893008,-2.658304,0.925605,0.974372
14,latitude_longitude____AOD,AOD,0.386819,-0.011551,1.385611,0.955981
15,latitude_longitude____PM2.5,PM2.5,46.610378,-1.906082,0.815273,0.998386
16,latitude_longitude_AOD_PM2.5_idw____AOD_PM2.5,AOD,1.570344,-16.182436,755.654360,0.010021
17,latitude_longitude_AOD_PM2.5_idw____AOD_PM2.5,PM2.5,2438.672487,-8846.370117,40183.690000,0.010021
18,latitude_longitude_AOD_PM2.5_idw____AOD,AOD,0.327303,0.247015,31.503624,0.251511
19,latitude_longitude_AOD_PM2.5_idw____PM2.5,PM2.5,2180.088301,-7038.937012,32113.475000,0.000000

No kernel connected

No kernel connected

No kernel connected

No kernel connected